import fs from "fs"
import path from "path"

const ROOT = path.resolve(__dirname, "..")
const CONTENT_DIR = path.join(ROOT, "content")
const OUT_DIR = path.join(ROOT, "src", "generated")
const OUT_FILE = path.join(OUT_DIR, "tutorialManifest.ts")

interface ManifestEntry {
  id: string
  compositionId: string
  title: string
  config: Record<string, unknown>
}

function titleCase(slug: string): string {
  return slug
    .split("-")
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join(" ")
}

function scanConfigs(category: "tutorials" | "shorts", prefix: string): ManifestEntry[] {
  const dir = path.join(CONTENT_DIR, category)
  if (!fs.existsSync(dir)) return []

  const entries: ManifestEntry[] = []
  const slugs = fs.readdirSync(dir, { withFileTypes: true }).filter((d) => d.isDirectory())

  for (const dirent of slugs) {
    const configPath = path.join(dir, dirent.name, "config.json")
    if (!fs.existsSync(configPath)) continue

    try {
      const raw = fs.readFileSync(configPath, "utf-8")
      const config = JSON.parse(raw)
      const id = config.id || dirent.name
      const title = config.title || titleCase(dirent.name)

      entries.push({
        id,
        compositionId: `${prefix}-${id}`,
        title,
        config,
      })
    } catch (err) {
      console.warn(`⚠ Skipping ${configPath}: ${err instanceof Error ? err.message : err}`)
    }
  }

  return entries.sort((a, b) => a.title.localeCompare(b.title))
}

const tutorials = scanConfigs("tutorials", "Tutorial")
const shorts = scanConfigs("shorts", "Short")

fs.mkdirSync(OUT_DIR, { recursive: true })

const lines: string[] = [
  "// AUTO-GENERATED by scripts/generateTutorialManifest.ts — do not edit",
  `// Generated at: ${new Date().toISOString()}`,
  "",
  'import type { TutorialConfig } from "../compositions/ClaudeCodeTutorial/schema"',
  'import type { ProductShortConfig } from "../compositions/ProductShort/schema"',
  "",
  "interface ManifestEntry<T> {",
  "  id: string",
  "  compositionId: string",
  "  title: string",
  "  config: T",
  "}",
  "",
  `export const tutorials: ManifestEntry<TutorialConfig>[] = ${JSON.stringify(
    tutorials.map((e) => ({ id: e.id, compositionId: e.compositionId, title: e.title, config: e.config })),
    null,
    2,
  ).replace(/"config": /g, '"config": ')} as ManifestEntry<TutorialConfig>[]`,
  "",
  `export const shorts: ManifestEntry<ProductShortConfig>[] = ${JSON.stringify(
    shorts.map((e) => ({ id: e.id, compositionId: e.compositionId, title: e.title, config: e.config })),
    null,
    2,
  )} as ManifestEntry<ProductShortConfig>[]`,
  "",
]

fs.writeFileSync(OUT_FILE, lines.join("\n"))
console.log(`Tutorial manifest written to ${OUT_FILE}`)
console.log(`  ${tutorials.length} tutorials, ${shorts.length} shorts`)
